### ISSUE TITLE
Top-down, fully-observable overhead view

### ISSUE THREAD

**Issue by maximecb** [maximecb/gym-miniworld#1]
This is a commonly requested feature. Many people would like to have a top-down-view/map where the agent's position is visible. This view would be fully observable.

Could be implemented as a method on environments, eg `get_top_view()` that returns a numpy RGB array.  Once this is implemented, we will also want to update the human view produced by `env.render('human')` to always show the top-down view on the side, in addition to the first-person view.

We will most likely want the resolution of the top view to be configurable in the environment's constructor. However, the small top view produced for the human render will necessarily be smaller. As a result, we will probably want to render these separately, in two separate frame buffers.

**Comment by lcswillems** [comment]
I was going to create an issue for this. I think it would be a great feature. In Minigrid, we have a fully observable view even if the agent doesn't have one.

**Comment by maximecb** [comment]
This is now working, there is an `env.render_top_view()` method that produced a top-down rendering. Wondering if I want this to be the default in `manual_control` or not, with only a small agent view in the corner, or try to display all 3 views somehow (full size, small agent view, top view).

**Comment by lcswillems** [comment]
When I execute the code, I get this:
```
Registered env: MiniWorld-CollectHealth-v0
Registered env: MiniWorld-FourRooms-v0
Registered env: MiniWorld-Hallway-v0
Registered env: MiniWorld-Maze-v0
Registered env: MiniWorld-MazeS3-v0
Registered env: MiniWorld-OneRoom-v0
Registered env: MiniWorld-PutNext-v0
Registered env: MiniWorld-TMaze-v0
Registered env: MiniWorld-ThreeRooms-v0
Registered env: MiniWorld-WallGap-v0
Falling back to non-multisampled frame buffer
Falling back to num_samples=8
Falling back to non-multisampled frame buffer
loading texture "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/textures/concrete_1.png"
loading texture "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/textures/floor_tiles_bw_1.png"
loading texture "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/textures/concrete_tiles_1.png"
```
There are some "Failing back ...".

**Comment by maximecb** [comment]
Yes this is expected behavior. I haven't made the top-down view the default yet, because I'm not sure if I want to remove the full-sized view or how to arrange things in the window in a way that makes sense.

If you want to see it, comment out line 1196 and uncomment line 1197:
https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/miniworld.py#L1196

Some of the more interesting maps to see top-down are `MiniWorld-ThreeRooms-v0` and `MiniWorld-Maze-v0`.

**Comment by maximecb** [comment]
@ankitv I now have a working maze environment and a top view. I think you were interested in those features. Would like to have your feedback if you have time: https://github.com/maximecb/gym-miniworld/blob/master/images/maze_top_view.jpg
