### ISSUE TITLE
Default verbose-off

### ISSUE THREAD

**Issue by alexandervandekleut** [maximecb/gym-miniworld#14]
Hello,

The terminal gets quite cluttered with all of the textual information being printed out during runtime. If this text is there for debugging purposes, is it possible for it to be turned on/off with some kind of verbosity flag?

Thanks!

**Comment by maximecb** [comment]
Can you copy/paste the text being printed?

**Comment by maximecb** [comment]
I've disabled most of the logging. Let me know if you run into other issues.
