### ISSUE TITLE
Occlusion queries, ability to get list of visible objects

### ISSUE THREAD

**Issue by maximecb** [maximecb/gym-miniworld#18]
@mweiss17 has requested this feature for his navigation research project, and there are many other legitimate use cases, so it's time to take a deeper look.

Proposed API:
```
def get_visible_entities(self):
    raise NotImplemented
    return list of visible entities
```

Doing this will necessarily involve performing an extra rendering pass so that we can check if pixels from any object end up being drawn on the screen.

There is a standard OpenGL way of doing this using occlusion queries:
https://vertostudio.com/gamedev/?p=177

One technique to speed this up is to use results from the previous frame (previous camera and object position) which are slightly out of date:
https://www.reddit.com/r/opengl/comments/1pv8qe/how_do_occlusion_queries_work/
http://www.visualizationlibrary.org/documentation/pag_guide_occlusion_culling.html

The rendering pass for occlusion queries should be done with texturing disabled. It should also ideally use some kind of a bounding volume for objects. Right now the bounding volume in MiniWorld is a bounding cylinder. The downside is that this is any bounding volume is an approximation. In some cases, it will report objects as visible when they are not. Note that even without this definition, the OpenGL definition of an object being visible is if any single pixel is visible.

@mweiss17 It could be a problem for navigation if one single pixel being drawn makes an object "visible". One way we might be able to get around it is by having bounding volumes that are slightly too small, or to check if objects are visible in N successive frames. That is, don't expect the follower to have seen the object unless we are "really extra sure" that this object has been visible for a little while and from multiple camera positions while the agent was moving. In other words, MiniWorld will use the OpenGL definition of visible, but you can do some post-processing to be more conservative as for that it means for your agent to consider something visible. You can also use other heuristics such as distance between the agent and the object, and approximate size of the object on screen (based on distance + height, trigonometry).

Step 1 for me in implementing this is probably to refactor MiniWorld a bit so that we have a better architecture for doing multiple rendering passes. Otherwise, we can do occlusion queries based on the rendering of the last frame, and using more conservative heuristics, this may work fairly well.

**Comment by maximecb** [comment]
My understanding of GL occlusion queries so far: allocate a query ID for each object. Then wrap the rendering of that object in glBeginQuery/glEndQuery. We can then verify the result of the said query after rendering, using

```
glGenQueries(1, &occlusionQuery);

# Ideally need to release this after in env.close()
glDeleteQueries(1, &occlusionQuery);

glBeginQuery(GL_ANY_SAMPLES_PASSED, occlusionQuery);
# Do the render here
 glEndQuery(GL_ANY_SAMPLES_PASSED);

# Ask for the result later
glGetQueryObjectuiv(entity.occlusionQuery, GL_QUERY_RESULT, &passed);
```

The MiniWorldEnv class should be able to handle all of this, without any special code needed in the entity objects themselves, which is nice.

**Comment by mweiss17** [comment]
@maximecb This looks great! I think in terms of visibility, a good conservative definition would be "is the center-point visible". I.e., we define the bounding volume to be the center-point. If we adopted that strategy, then I think there may be clever alternatives to this type of querying. I believe this would be similar to common problem of Mouse Picking with Ray Casting, but without the mouse, and with more objects :) 

http://antongerdelan.net/opengl/raycasting.html

That said, the OpenGL occlusion queries implementation may be easier.

**Comment by maximecb** [comment]
The issue with ray casting is that MiniWorld is implemented in Python, and just traversing the scene and computing intersection tests could be very slow. Going with a very small bounding volume could make sense. Then we would need some separate bounding volume size that we use for visibility testing. I guess we can start with every object having a bounding cube of the same small size for a first test implementation.

**Comment by mweiss17** [comment]
yes, that makes sense!

**Comment by maximecb** [comment]
@mweiss17 I implemented a first version of a visibility check here: https://github.com/maximecb/gym-miniworld/commit/f6c56ac6eb5972dcf1e0e64dc20999b82b8df0ad

There is a new method `env.get_visible_ents()` which returns a Python set of visible objects. It draws a small bounding box for each object and uses that for the visibility check. In my simple environments this seems to work pretty well. The one issue that I can see is that if you had multiple objects occluding each other, this small bounding box trick would not work as well, because the bounding boxes would not occlude each other. It still seems like an OK visibility approximation to me, but maybe you can try it and let me know.

The other thing is this is currently not optimized for performance. Maybe you can try it when you get a chance or when you get back, and if it works well enough for your needs, I will optimize it. I think I can make it run at least 10x faster using display lists.

**Comment by mweiss17** [comment]
Amazing -- thank you! I will give it a shot after I return from Japan.
