### ISSUE TITLE
ERROR: "Connection reset by peer"

### ISSUE THREAD

**Issue by sunchipsster1** [maximecb/gym-miniworld#22]
Hello! Thank you so much for creating this awesome resource for the community, it has been a really great help!

I am encountering a problem: I am using the main.py RL script with the Hallway maze, and it seems to work well. However, trying any other maze, for example -- 4 rooms, yields the following error: (see attached image). Does anyone know the source of this error and how to fix it? 

Thank you!

![image](https://user-images.githubusercontent.com/56416888/79061361-8e559e80-7c5d-11ea-87f5-6eace0039c26.png)

**Comment by maximecb** [comment]
Hi @sunchipsster1 !

There is one other similar issue here: https://github.com/maximecb/gym-miniworld/issues/16

It's also possible something might be producing an error and you're not seeing the error message because it happens in another process that doesn't have access to print on the console. We'd have to find out what that error message is.

Does the error happen if you set the number of processes to 1 for the RL script? Does it print a different error message? Are you able to run the 4 rooms environment without issue using the `manual_control.py` script?

**Comment by sunchipsster1** [comment]
Hi @maximecb !
Thank you so much for your kind reply, and the suggestions!
I have tried your suggestions, and the results are as follows: 
with Hallway, it is able to be successfully trained, even when num-processes is 1, or > 1 (e.g. 16) (1st attached image).
I tried to run Fourrooms in manual_control, and it works (2nd attached image). However, when I ran training, it received an error (3rd image attached). 

In a peculiar observation, I created a "copy" of the hallway.py file called hallwayCopy.py None of the internal parameters of the room were changed, only the name of the file (4th attached image). However, when I ran this in training, this too received an error (5th attached image). 

Do you know where the error might lay? Thank you again for all your kind help! 

![image](https://user-images.githubusercontent.com/56416888/79072673-4318ab80-7cb0-11ea-85e8-fed516a0775f.png)

![image](https://user-images.githubusercontent.com/56416888/79072534-80c90480-7caf-11ea-895e-baf1d7709854.png)

![image](https://user-images.githubusercontent.com/56416888/79072754-bde1c680-7cb0-11ea-9090-01d59d480c62.png)

![image](https://user-images.githubusercontent.com/56416888/79072362-a73a7000-7cae-11ea-92f2-2017f629dbc4.png)

![image](https://user-images.githubusercontent.com/56416888/79072636-1b294800-7cb0-11ea-8156-40c0aca1b7a6.png)

**Comment by maximecb** [comment]
I think you just have the name of the environments wrong. The
capitalization matters, so it would be FourRooms-v0, and hallwayCopy-v0. It
has to exactly match the class name.

**Comment by sunchipsster1** [comment]
Hi @maximecb indeed, when I corrected the FourRooms-v0 as you instructed, it now works, thank you!

However, the hallwayCopy-v0 still does not, and I hope to understand why because I would like to be able to create *new* environments :) I was hoping you might be able to help me on this issue? Thank you again for everything and apologies if the solution ends up being some extremely trivial issue!

I have attached the names (capitalized appropriately, I hope, for the class name) of the relevant files to this email. I have attached the error which results. 

![image](https://user-images.githubusercontent.com/56416888/79075014-f63bd180-7cbd-11ea-94f3-d9146e0d5140.png)

![image](https://user-images.githubusercontent.com/56416888/79075046-3a2ed680-7cbe-11ea-8d11-2eedd1e91a16.png)


![image](https://user-images.githubusercontent.com/56416888/79075082-78c49100-7cbe-11ea-9691-2a10a2f5aae0.png)

![image](https://user-images.githubusercontent.com/56416888/79075106-b1fd0100-7cbe-11ea-9591-2bc92b5892fb.png)


![image](https://user-images.githubusercontent.com/56416888/79075150-f4bed900-7cbe-11ea-9a78-c9c091fb765a.png)

**Comment by maximecb** [comment]
Yes, you should import the Python file in `__init__.py`. Then, when launching the environment, the name you use should match the class name (not the Python script name). Your example looks correct.

**Comment by sunchipsster1** [comment]
Hi Maxime, it now works :)
For others who might naively encounter this -- after creating a new envs file, rerunning pip3 install -e . seems necessary. 
Thank you so much!

**Comment by maximecb** [comment]
Glad it's working :)
