### ISSUE TITLE
ACTIONS in "make_vec_envs" vs regular Actions

### ISSUE THREAD

**Issue by sunchipsster1** [maximecb/gym-miniworld#23]
Hi :) Thank you again for this great resource. I have a question about the definition of actions in the manual control script vs the definition of actions in the RL training script. I hope to be able to use the "learned" policy, with defined actions --> and be able to visualize the policy learned in a "agent" point of view like the manual control script. 

For this purpose (I don't know if this is a particularly dumb solution, or if there is a more miraculous and easier solution), but I imagined I would feed the actions from the trained policy --> into the manual control script, but the problem is that the actions from the RL script are integers [0], [1], [2] in the Hallway problem. How do these correspond to actions like move_forward, move_left etc.? What is the mapping?  

Thank you very much for the kind help!

![image](https://user-images.githubusercontent.com/56416888/79094150-90366500-7d24-11ea-856f-77b4c13eeef7.png)

![image](https://user-images.githubusercontent.com/56416888/79094186-b0feba80-7d24-11ea-89b1-cff4e312d9e3.png)

**Comment by maximecb** [comment]
Hi again @sunchipsster1,

So the first thing I should mention is that there is a `visualize.py` script that is made for visualizing trained policies, so this probably does what you want: https://github.com/maximecb/gym-miniworld/blob/master/pytorch-a2c-ppo-acktr/visualize.py

As for the mapping of names to actions, it happens here: 
https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/miniworld.py#L437

This uses an IntEnum, so each name gets assigned an integer value. This is so we can avoid having to refer to actions by number and instead have something more readable in the code.

**Comment by sunchipsster1** [comment]
Hi @maximecb , 
Thank you again for your kind reply! You have a beautiful function "enjoy.py" which produces examples of the policy being played, thank you for writing this!

I tried to use visualize.py. I just wanted to confirm: in order to use visdom_plot, it is not correct to simply feed it the data from the pt files, e.g. MiniWorld-Hallway-v0.pt correct? 

It seems in line 56 of visualize.py, one must have stored data into csv files to begin with, in order to load this data into visualize.py. Therefore, I want to confirm that we are meant to modify the code to collect the data they want to visualize (like saving episode_rewards into a csv) in order to then use visualize.py, correct? 

Thank you again!

**Comment by maximecb** [comment]
Right, actually, I think `enjoy.py` is the script that you want. The `visualize.py` script is for showing graphs. I've never used it. It's possible that it's broken.
