### ISSUE TITLE
assert res == GL_FRAMEBUFFER_COMPLETE failing

### ISSUE THREAD

**Issue by ezliu** [maximecb/gym-miniworld#24]
Hi,

I'm trying to run MiniWorld remotely on a Ubuntu machine. I've followed the Installation guide. Following the Troubleshooting guide, I've installed xvfb and mesa-utils, but I'm running into the following error:

```
(venv) evanliu@iris:/iris/u/evanliu/code/gym-miniworld$ xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" ./run_tests.py                                                                                                    [0/1951]
Falling back to non-multisampled frame buffer
Traceback (most recent call last):
  File "./run_tests.py", line 9, in <module>
    env = gym.make('MiniWorld-Hallway-v0')
  File "/iris/u/evanliu/code/venv/lib/python3.5/site-packages/gym/envs/registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "/iris/u/evanliu/code/venv/lib/python3.5/site-packages/gym/envs/registration.py", line 87, in make
    env = spec.make(**kwargs)  
  File "/iris/u/evanliu/code/venv/lib/python3.5/site-packages/gym/envs/registration.py", line 59, in make
    env = cls(**_kwargs)       
  File "/iris/u/evanliu/code/gym-miniworld/gym_miniworld/envs/hallway.py", line 19, in __init__
    **kwargs                   
  File "/iris/u/evanliu/code/gym-miniworld/gym_miniworld/miniworld.py", line 502, in __init__
    self.obs_fb = FrameBuffer(obs_width, obs_height, 8)
  File "/iris/u/evanliu/code/gym-miniworld/gym_miniworld/opengl.py", line 216, in __init__
    assert res == GL_FRAMEBUFFER_COMPLETE, FB_ERROR_ENUMS.get(res, res)
AssertionError: 0
```

Thanks for the help!

**Comment by maximecb** [comment]
Hi Evan,

Do you know what kind of graphics card is installed on this machine? I've tested it on nvidia and Intel graphics, but not other vendors. I will need your help to debug this, if you have time.

Would you mind adding some prints throughout the try block here:
https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/opengl.py#L136

So we can know how far the execution got before an exception was thrown and we ended up here:
https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/opengl.py#L182

**Comment by ezliu** [comment]
Hi Maxime,

Thanks so much for your help! It looks like it's failing on the assert here: https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/opengl.py#L138

I will get back to you with the graphics card.

**Comment by ezliu** [comment]
Adding relevant information:

```
$ xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" glxinfo
name of display: :99
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  37
  Current serial number in output stream:  38
```

**Comment by ezliu** [comment]
Closing this. The fix is to reinstall the NVIDIA GPU drivers with the `no-opengl-libs` flag.

Thanks for the help, Maxime! This environment is fantastic.

**Comment by maximecb** [comment]
Thanks Evan. Happy you were able to find a fix ^_^

**Comment by ptigas** [comment]
Hi, thank you for this environment, it's great!

Is there a solution to this problem without having to re-install nvidia-drivers? unfortunately, I'm trying to share this on a shared cluster and playing with the drivers is not an option.

**Comment by ezliu** [comment]
FWIW, I'm not aware of any such solution. I know there's an effort to add support for EGL on pyglet, which would avoid this, but it seems like this won't be happening for a while.

I'd also love to hear if @maximecb has any alternate solutions, though I think not.

**Comment by ptigas** [comment]
I figured out a way which doesn't require messing with the drivers. If you upgrade pyglet to `1.5.11`, you can do the following before invoking `gym_miniworld`

```
import pyglet
pyglet.options['headless'] = True
from gym_miniworld.envs.tmaze import TMaze
...
```

**Comment by maximecb** [comment]
I opened that issue on Pyglet two years ago suggesting they should support EGL, and they've just released experimental support. Glad it's working 👍

**Comment by ezliu** [comment]
Oh, this is great! Glad I was wrong :)
