### ISSUE TITLE
Can we train an agent without opening a window?

### ISSUE THREAD

**Issue by PrettyPrettyMeng** [maximecb/gym-miniworld#26]
Hi there, is it possible to train an RL agent without opening the simulation window? I'm trying to do training on my server but it can be problematic to open a window there.

Any help or response will be highly appreciated. Thanks!

**Comment by maximecb** [comment]
Yes, you can train without a window.

**Comment by PrettyPrettyMeng** [comment]
> Yes, you can train without a window.
> 
> Calling `env.step()` does not open a window.

Thanks for your quick reply! I would like to know does this error occurs because of trying to open a window?

pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

which is also mentioned in #13 .

**Comment by maximecb** [comment]
That has to do with trying to connect to a display for rendering. Have you tried using `xvfb-run` as outlined here?

https://github.com/maximecb/gym-miniworld/blob/master/docs/troubleshooting.md#nosuchdisplayexception-cannot-connect-to-none

**Comment by PrettyPrettyMeng** [comment]
> That has to do with trying to connect to a display for rendering. Have you tried using `xvfb-run` as outlined here?
> 
> https://github.com/maximecb/gym-miniworld/blob/master/docs/troubleshooting.md#nosuchdisplayexception-cannot-connect-to-none

Thanks again. Actually the cluster I use cannot install xvfb for some reason. I wonder whether it is possible to do training without displaying or rendering.

**Comment by maximecb** [comment]
You should contact the cluster administrators and try to get them to install xvfb. It's necessary for many environments that use OpenGL for rendering, unfortunately.

I'm trying to get the people behind the pyglet package to remove this dependency, by implementing EGL support, but that hasn't been moving.

**Comment by PrettyPrettyMeng** [comment]
> You should contact the cluster administrators and try to get them to install xvfb. It's necessary for many environments that use OpenGL for rendering, unfortunately.
> 
> I'm trying to get the people behind the pyglet package to remove this dependency, by implementing EGL support, but that hasn't been moving.

Thank you so much! I will try.
