### ISSUE TITLE
Releasing a new pypi package

### ISSUE THREAD

**Issue by shagunsodhani** [maximecb/gym-miniworld#33]
Thank you for creating the repo. It is extremely useful. Could you please release a new version of this on pypi? [The current version](https://pypi.org/project/gym-miniworld/) is about 2 years old.

**Comment by maximecb** [comment]
Hi @shagunsodhani. Let's try to fix #34 and then I'll update the pip package.

**Comment by maximecb** [comment]
Pip package updated!

**Comment by shagunsodhani** [comment]
Thanks @maximecb  :)
