### ISSUE TITLE
Customizing maze from txt files and retrieve depth image

### ISSUE THREAD

**Issue by cgxuvector** [maximecb/gym-miniworld#38]
Hi,

Nice work! I am happy to see simple and customizable domains like this. I have the following questions:
1. It seems the maze env is created by creating #(row x col) rooms and then they are connected using the backtracking algorithm. Is it possible to generate the maze from a txt file similar to deepmind lab? If not, could u please give me some hints of how to change it?
2. I still wonder if there is a way to retrieve the depth image. However, when I read the code in miniworld.py and maze.py. It seems the current version only provides RGB images. Could u please tell me how to obtain a depth image?  (I resolve this question thanks.)
Best,

**Comment by maximecb** [comment]
Hi @cgxuvector 

Basically each grid cell is a room with 4 walls. As we generate a random tree through the maze, we remove walls to connect adjacent grid cells along the path.

If you want to create mazes you can load from text files, I would copy the maze environment into a new file, and name the environment TextMaze or something like that. You can create environments that take arguments in their constructor and pass the arguments using [kwargs in gym.make](https://github.com/openai/gym/pull/1301). You'd want to add a `file_path` argument to load your text file from.

Then, you can load the text file, read it row by row using the `readlines()` function. You should create a grid of the appropriate size, and iterate through it. If a given cell is a wall, then the adjacent cells shouldn't be connected to it. There are other environments that illustrate how to add objects such as balls, cubes, keys, etc.

To get the depth map you would call `env.render_depth()`. [The method](https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/miniworld.py#L1207) will return a numpy array with depth for each pixel.

Let me know if you have any other questions. If you do create such an environment feel free to submit a pull request when you are done :)

**Comment by cgxuvector** [comment]
Thanks for your feedback!
