### ISSUE TITLE
Panoramic observation

### ISSUE THREAD

**Issue by cgxuvector** [maximecb/gym-miniworld#39]
Hi,

I am writing to ask whether it is possible to get panoramic observation given the current position? I notice there is a function in miniworld.py called render_obs(). In the function, there is a method called         
gluLookAt(
            # Eye position
            *self.agent.cam_pos,
            # Target
            *(self.agent.cam_pos + self.agent.cam_dir),
            # Up vector
            0, 1.0, 0.0
        )
I try to modify the self.agent.cam_dir. However, it seems only modify cam_dir can not get a 360 view. I have the following thoughts:
1. Turning the agent 360 and capture the observations.
2. Place 4 cameras on the agent
3. Changing the camera yaw of the current agent
Could you please tell me which is doable in this repo? If nothing works, could you give me any suggestions?

Best,

**Comment by maximecb** [comment]
By changing the fov Y (vertical field of view angle) in gluPerspective you can make the view angle wider, up to almost 180 degrees I believe: https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/miniworld.py#L1184

However, if you want to get 360 degrees, you will need to render multiple views. The `cam_dir` is a direction vector that is computer from `self.agent.dir`, which is the direction angle the camera will be pointed at. If you change this angle, you can change the direction the agent is looking to achieve what you want.

**Comment by cgxuvector** [comment]
Thanks! I resolve the issue.
