### ISSUE TITLE
Parallel environment with multiprocessing.Pipe?

### ISSUE THREAD

**Issue by ruoshiliu** [maximecb/gym-miniworld#44]
Hi there, thank you so much for sharing the code! I was trying to run parallel environment using pipe as done in: https://github.com/lcswillems/rl-starter-files. However, that doesn't seem to work. I got EOFerror for all process other than the main one. Any idea why and how to fix it? Thanks in advanced!

Here's the relevant code:

```
class ParallelEnv(gym.Env):
    def __init__(self, envs):
        assert len(envs) >= 1,
        self.envs = envs
        self.observation_space = self.envs[0].observation_space
        self.action_space = self.envs[0].action_space

        self.locals = []
        for env in self.envs[1:]:
            local, remote = Pipe()
            self.locals.append(local)
            p = Process(target=worker, args=(remote, env))
            p.daemon = True
            p.start()
            remote.close()

    def reset(self):
        for local in self.locals:
            local.send(("reset", None))
        results = [self.envs[0].reset()] + [local.recv() for local in self.locals]
        return results

    def step(self, actions):
        for local, action in zip(self.locals, actions[1:]):
            local.send(("step", action))
        obs, reward, done, info = self.envs[0].step(actions[0])
        print(obs.shape)
        if done:
            obs = self.envs[0].reset()
        results = zip(*[(obs, reward, done, info)] + [local.recv() for local in self.locals])
        return results

    def render(self):
        raise NotImplementedError
```

**Comment by maximecb** [comment]
When opening an issue, the first thing that you should do is always to provide some details about which platform you are on, and what command you used to run the program.

The error could happen for a number of reasons. The EOFError likely means all the other processes crashed, but they aren't able to log an error to the console. 

This is one example:
https://github.com/lcswillems/rl-starter-files/issues/48

You might be able to log the output of the crashing processes like this:
https://stackoverflow.com/questions/1501651/log-output-of-multiprocessing-process

Alternatively, you might have better luck with the RL code found in the babyai repository:
https://github.com/mila-iqia/babyai

**Comment by ruoshiliu** [comment]
Thank you for the prompt response. Here's what I did:
1. git cloned [rl-starter-files](https://github.com/lcswillems/rl-starter-files)
pip3 install -r requirements.txt
2. git clone https://github.com/lcswillems/torch-ac.git
cd torch-ac
pip3 install -e .
cd ..
3. git clone https://github.com/maximecb/gym-miniworld.git
cd gym-miniworld
pip3 install -e .
cd ..
4. added `import gym_miniworld` in [envs.py](https://github.com/lcswillems/rl-starter-files/blob/master/utils/env.py)
5. run `PYOPENGL_PLATFORM=egl CUDA_VISIBLE_DEVICES=0 PYTORCH_JIT=0 python -m scripts.train --algo a2c --env MiniWorld-TMaze-v0 --save-interval 100 --frames 10000000 --procs 16 --recurrence 4 --frames-per-proc 4 --log-interval 20 --lr 1e-4` (running on linux through ssh with offscreen rendering)

The error comes from this line: https://github.com/lcswillems/torch-ac/blob/85d0b2b970ab402e3ab289a4b1f94572f9368dad/torch_ac/utils/penv.py#L8. I'm pretty sure it's different from [lcswillems/rl-starter-files#48](https://github.com/lcswillems/rl-starter-files/issues/48) because I was able to receive output from the main process.

**Comment by ruoshiliu** [comment]
[Update] it seems all other processes crashed at this line: https://github.com/maximecb/gym-miniworld/blob/d640e5bb143e218aa1cb4127f8251b495a34fd9a/gym_miniworld/miniworld.py#L1083

**Comment by maximecb** [comment]
Did it crash inside the resolve method, or when doing the call? Can you print `frame_buffer` just before the call?

**Comment by ruoshiliu** [comment]
Sorry for the delay. Here's the output of printing frame_buffer:
`<gym_miniworld.opengl.FrameBuffer object at 0x7f9e1a425fa0>`

**Comment by ruoshiliu** [comment]
It crashed inside the resolve method at this line: https://github.com/maximecb/gym-miniworld/blob/d640e5bb143e218aa1cb4127f8251b495a34fd9a/gym_miniworld/opengl.py#L300-L308

**Comment by maximecb** [comment]
This is probably related to your graphics card or driver. I can't really help you debug it because I have no way to test on your machine. If you're doing training or running on a remote machine, you might have better luck running the code with xvfb: https://github.com/maximecb/gym-miniworld/blob/master/docs/troubleshooting.md#nosuchdisplayexception-cannot-connect-to-none
