### ISSUE TITLE
What are list of environments currently solvable by PPO

### ISSUE THREAD

**Issue by nikhilrayaprolu** [maximecb/gym-miniworld#49]
In the list of [current environments](https://github.com/maximecb/gym-miniworld/blob/master/docs/environments.md) what are practically solvable by current RL algorithms?

**Comment by maximecb** [comment]
I'm not sure. There's a handful of papers citing miniworld: https://scholar.google.ca/scholar?oi=bibs&hl=en&cites=16015822555890054842

But to my knowledge, outside of the trivial environments (i.e. corridor), these are quite hard to solve because of the sparse rewards.
