### ISSUE TITLE
Repeat an action when key is held

### ISSUE THREAD

**Issue by lcswillems** [maximecb/gym-miniworld#5]
If I hold the up arrow, it would be nice if the agent continues to go forward. Otherwise, if I want the agent to cross the room, I need to press the up arrow a lot of times. This can also be done for all the actions triggered by a key press event.

**Comment by maximecb** [comment]
Pyglet doesn't have any built-in way to handle key repeat. I added a temporary solution which is to repeat forward/back actions 3 times when a shift key is held down. That makes it possible to move faster without having to bash the up arrow key.

I might look into implementing a proper key repeat solution later. This would require instantiating a timer event when a key is pressed and unregistering the timer when the key is released, which might be feasible.

**Comment by maximecb** [comment]
Going to have to revert my previous solution because there is an issue with Pyglet and the double buffering on Mac.  Sigh.

**Comment by maximecb** [comment]
Ok, I implemented a more proper key repeat mechanism. Should do what you originally requested @lcswillems.

**Comment by lcswillems** [comment]
Great!!
