### ISSUE TITLE
error when trying to import  gym_miniworld on Google Colab

### ISSUE THREAD

**Issue by ibagur** [maximecb/gym-miniworld#52]
Before, I had no problems in running `minigrid` over Colab, however I have tried several options in order to run `Miniworld` over Colab but have not succeeded. At the beginning of my Colab notebook, I first install the following libraries:

```
!pip install rarfile --quiet
!pip install stable-baselines3 > /dev/null
!pip install box2d-py > /dev/null
!pip install gym pyvirtualdisplay > /dev/null 2>&1
!sudo apt-get install -y xvfb python-opengl ffmpeg > /dev/null 2>&1
!pip install gym-miniworld > /dev/null 2>&1
```

Then, the error appears right when importing the libraries:

```
import gym
import gym_miniworld
```

The error I get is the following:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-13-7f542eec6530>](https://fv0dqg4ruxm-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220224-060059-RC00_430667398#) in <module>()
      1 import gym
----> 2 import gym_miniworld

3 frames
[/usr/local/lib/python3.7/dist-packages/pyglet/gl/__init__.py](https://fv0dqg4ruxm-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220224-060059-RC00_430667398#) in <module>()
    233 elif compat_platform == 'darwin':
    234     from .cocoa import CocoaConfig as Config
--> 235 del base  # noqa: F821
    236 
    237 

NameError: name 'base' is not defined

```

Any suggestion on how to handle this? Many thanks!

**Comment by maximecb** [comment]
Hmmm it seems like pyglet can't run on your config, presumably because there's no display. 

Have you tried rendering offscreen: https://github.com/maximecb/gym-miniworld#offscreen-rendering

Or using xvfb?

**Comment by amy12xx** [comment]
I've been able to get around this by first adding your code to a script, and then executing on Colab as:

!xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" python3 script_name.py 

(there may be other ways too).

**Comment by maximecb** [comment]
xvfb creates a virtual display which is often necessary when running on clusters.

Does it work if you use `egl` instead of xvfb? i.e.

```
PYOPENGL_PLATFORM=egl python3 script_name.py
```

**Comment by amy12xx** [comment]
> xvfb creates a virtual display which is often necessary when running on clusters.
> 
> Does it work if you use `egl` instead of xvfb? i.e.
> 
> ```
> PYOPENGL_PLATFORM=egl python3 script_name.py
> ```
> 
> We should probably update the instructions in the readme to explicitly mention clusters and colab.

Just tested on Colab, this works too.

**Comment by maximecb** [comment]
I updated the readme to make it clearer that this is needed to run on Colab and on clusters 👍
