### ISSUE TITLE
running problem

### ISSUE THREAD

**Issue by Tommyliu23** [maximecb/gym-miniworld#55]
hello!when I follow your instruction :::::

python3 main.py --algo ppo --num-frames 5000000 --num-processes 16 --num-steps 80 --lr 0.00005 --env-name MiniWorld-Hallway-v0

it went wrong as follow::::::::
Failed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionFailed to establish dbus connectionCreating frame stacking wrapper
Saving model

/home/lab1207/anaconda3/lib/python3.9/site-packages/numpy/core/_asarray.py:171: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  return array(a, dtype, copy=False, order=order, subok=True)
/home/lab1207/anaconda3/lib/python3.9/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
Traceback (most recent call last):
  File "/home/lab1207/liujiong/gym-miniworld/pytorch-a2c-ppo-acktr/main.py", line 227, in <module>
    main()
  File "/home/lab1207/liujiong/gym-miniworld/pytorch-a2c-ppo-acktr/main.py", line 163, in main
    np.mean(episode_rewards),
  File "<__array_function__ internals>", line 5, in mean
  File "/home/lab1207/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3419, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
  File "/home/lab1207/anaconda3/lib/python3.9/site-packages/numpy/core/_methods.py", line 188, in _mean
    ret = ret.dtype.type(ret / rcount)
AttributeError: 'torch.dtype' object has no attribute 'type'

I dont know what does it mean,could you please help me solve this problem?
hoping for your reply,thanks again for your notice!!!!

**Comment by maximecb** [comment]
No longer maintaining this reinforcement learning code, would recommend using another RL algorithm implementation
