### ISSUE TITLE
Oracle solution / Shortest path algorithm

### ISSUE THREAD

**Issue by Mariusmarten** [maximecb/gym-miniworld#58]
Hi, 

very nice project! I'm using it for an exploration task and I was wondering whether an oracle exists to determine the shortest path between the agent and the goal state (or any other position on the map)? Or how such an implementation could best be approached?

Best,

**Comment by maximecb** [comment]
Hello Marius. There is unfortunately no oracle as that would be very difficult to implement for any path that is not trivial. Your best bet would be to compare against a trained policy.

**Comment by Mariusmarten** [comment]
Thank you, for the quick response! While looking into the problem I already expected such an answer but I was hoping I missed something.
