### ISSUE TITLE
Position of target

### ISSUE THREAD

**Issue by jooker23** [maximecb/gym-miniworld#60]
It was asked by other friends, but I did not understand clearly, for example, on the map of the four rooms, the target and the agent are defined as random. I want to set target position myself. so the target will always start at the same place as the agent randomly. How can I do that?
Please explain clearly, thx for help.

**Comment by maximecb** [comment]
You should look at the code for existing environments and how the `place_entity` function works:
https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/envs/fourrooms.py#L50

https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/miniworld.py#L845
