### ISSUE TITLE
Done=False on agent death in collecthealth

### ISSUE THREAD

**Issue by himanshusahni** [maximecb/gym-miniworld#7]
https://github.com/maximecb/gym-miniworld/blob/77083a1efb838389819479e43542b9bc5453d37e/gym_miniworld/envs/collecthealth.py#L72

done=True must be set here to start new episode.

**Comment by maximecb** [comment]
I was thinking that the agent could just keep training continuously in an endless episode. That way there isn't the overhead of regenerating the environment when the episode ends. Do you find that this is a problem?

**Comment by maximecb** [comment]
Ok. I will make the episode end when the agent dies, and probably after some very large number of steps, eg: 1000.

**Comment by maximecb** [comment]
Done.
