### ISSUE TITLE
agent 'dir' does not wrap around 2pi

### ISSUE THREAD

**Issue by himanshusahni** [maximecb/gym-miniworld#8]
https://github.com/maximecb/gym-miniworld/blob/77083a1efb838389819479e43542b9bc5453d37e/gym_miniworld/miniworld.py#L639

would be nice if yaw was in some finite range (0,2pi). I don't think this affects any navigation logic rn but it would make it easier to look at.

**Comment by maximecb** [comment]
I don't love the idea of enforcing this constraint on every object that has a `dir` value, or just on the agent, so I'm going to do is write some code to convert it before it gets displayed.

**Comment by maximecb** [comment]
Done. One-line change :)
